# see https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates
version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  target-branch: "dev"
  schedule:
    interval: daily
  open-pull-requests-limit: 20
  ignore:
  - dependency-name: org.springframework.security.oauth:spring-security-oauth2
  - dependency-name: com.alibaba.cloud:spring-cloud-alibaba-dependencies
    versions: ["2021.1"]
