server:
  port: 18080

sde:
  example:
    run-on-startup: true

logging:
  level:
    com.power4j.fist3.examples.sde.web: DEBUG
    com.power4j.fist.sde: DEBUG

fist:
  sde:
    enabled: true
    web:
      enabled: true
      default-policy-id: body-strict-v1
    policies:
      body-strict-v1:
        request-body-mode: REQUIRED
        response-body-mode: FOLLOW_REQUEST
        crypto-enabled: true
        signature-enabled: true
        crypto-handler: aesGcmCryptoHandler
        signature-handler: hmacSha256SignatureHandler
        key-resolver: staticSecureKeyResolver
        nonce-generator: secureRandomNonceGenerator
        replay-guard: replayGuard
        timestamp-window: 5m
